// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message Error message
	//
	// Example: Bad request
	Message *string `json:"message,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// EventUuid UUID of the event
	EventUuid *openapi_types.UUID `json:"event_uuid,omitempty"`

	// Name event name
	//
	// Example: local-storage:disk:added
	Name string `json:"name"`

	// Properties event properties
	//
	// Example: [{"name":"local-storage:vendor","value":"SanDisk"},{"name":"local-storage:model","value":"Cruzer"},{"name":"local-storage:uuid","value":"442e0e5b-9d3e-4fe8-b46f-9c4141fdecd7"},{"name":"casaos-ui:type","value":"notification-style-2"},{"name":"casaos-ui:title","value":"New disk found"},{"name":"casaos-ui:icon-1","value":"casaos-icon-disk"},{"name":"casaos-ui:message-1","value":"A new disk, SanDisk Cruzer, is added."}]
	Properties []Property `json:"properties"`

	// SourceID associated source id
	//
	// Example: local-storage
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this event took place
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Property defines model for Property.
type Property struct {
	// Name Name of the property
	Name *string `json:"name,omitempty"`

	// Value Value of the property
	Value *string `json:"value,omitempty"`
}

// EventUuid Example: 123e4567-e89b-12d3-a456-426655440000
type EventUuid = openapi_types.UUID

// Serial Example: 1234567890
type Serial = string

// BadResponse defines model for BadResponse.
type BadResponse = BaseResponse

// DeleteEventOK defines model for DeleteEventOK.
type DeleteEventOK = Event

// OKResponse defines model for OKResponse.
type OKResponse = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// Form Form of the events to get
	Form *time.Time `form:"form,omitempty" json:"form,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// DeleteEventBySerial Delete an event
	// (DELETE /event/local_storage/{serial})
	DeleteEventBySerial(ctx echo.Context, serial Serial) error
	// DeleteEvent Delete an event
	// (DELETE /event/{event_uuid})
	DeleteEvent(ctx echo.Context, eventUuid EventUuid) error
	// GetEvents Get all events
	// (GET /events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteEventBySerial converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventBySerial(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serial" -------------
	var serial Serial

	err = runtime.BindStyledParameterWithOptions("simple", "serial", ctx.Param("serial"), &serial, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serial: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventBySerial(ctx, serial)
	return err
}

// DeleteEvent converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_uuid" -------------
	var eventUuid EventUuid

	err = runtime.BindStyledParameterWithOptions("simple", "event_uuid", ctx.Param("event_uuid"), &eventUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEvent(ctx, eventUuid)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Optional query parameter "form" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "form", ctx.QueryParams(), &params.Form, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter form: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(options.BaseURL+"/event/:event_uuid", wrapper.DeleteEvent, options.OperationMiddlewares["deleteEvent"]...)
	router.GET(options.BaseURL+"/events", wrapper.GetEvents, options.OperationMiddlewares["getEvents"]...)
	router.DELETE(options.BaseURL+"/event/local_storage/:serial", wrapper.DeleteEventBySerial, options.OperationMiddlewares["deleteEventBySerial"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fhfb9s2EP8qBLeHDZAs2VHSREAfmqYtjABJsbQbsDgwzuLZZiORKkm5dQ1/94EUbcu2DKdF1r0sMBBL",
	"vH/k/e7uRy9oJotSChRG03RBS1BQoEHlnnCGwgyrijP7xFBnipeGS0FT+vFj/4rIMTFTJE6OGEkmaGhA",
	"uV0vwUxpQAUUSNOmpYAq/FxxhYymRlUYUJ1NsQDn8CsUZW4Vur0TTE7PXoR4fjEKuz12EkJyehYmvbOz",
	"09MkieM4pgEdS1WAoSn1ps28tNraKC4mdLkMqEbFId+P/869X+0glxnkRBupYILtW/CGnhy+jf78Im4J",
	"amlt6FIKje6YL4H94Z/tYyaFQWHsVyjLnGdgQ44+aRv3ouHuV4VjmtJfok0Oo3pVR5egcW3Uudze/iUw",
	"YjeC2tBlQK8wR4NvbJZur58tCGevzbtbIMw5Zdb/7fVPP4Hba+t4JXEjzVtZCfYE9+ssL2iBWlvApPRG",
	"GlIbWAbPFGDD5Nqmx0tD0RatkiUqw2s0rWPaRfwbpaQiq+WggdYmGCw2gd2KfL7C935N+Tdy9AkzB586",
	"0XuhfFf/OF7Nq1LcNVW3H7fW3JWr6dDXdMq4fkyBMWw1vB13m/mGRMPJ/WLVHra9zVAwqWhAZ5BXdvkO",
	"xBXXj3QZHNAoJMO8ofBaVd9QHZb3R7QST5Iexng6Ci/YCYbJGM/DUXI2Di+ypJt0xwwz9qJpLAMNUocV",
	"T91ZbAwJafjYQz7UZp5j2DugyE3e1LzBL8SeMhn7OmjR4ZkUYbeh5Jfce7ZzQBs1D9otzVdEeIcB8adL",
	"6kMLCNfEpbpDlw8B5QYLfawa39f5ndMNvkEpcM9aVirD/tU+NkBrmXEwyEgtRFxWDoCwDXmGF6gNFOW+",
	"8fUSMVOu11NWPpIyhwybBcPAYGjlW2fgZmLdb/biq2kL+w8ttb0+mL3ybq/GGyhwVdjlSrdl4z6Pu+p/",
	"2tfH9fe7kJv1WaW4md/ZnNYxQpah1kMjH9E1bzfYpwgM1Wa0v6rMVCr+zYF+4wtKfo3zujVzMZb7wQ6q",
	"OD7JSp6ZSqF7wIEg9q9e8ZgokHF4OaC/lQrHqHSYyVyq0EEPU8JAPf4+oESrTKN5OaBTY0qdRpGCL50J",
	"N9NqVGlUfix1MllE/Qz/mkKOHzCbRrmcyKgALqK6Yvy/4QiEQDW05oeCT6ZmeB7H5ddOKSYD+sPR5tbS",
	"vxiu+cKdi+Eor/BIxLyYEMhtDK9Bw+1dHdV/EFIdTrSLhA+2brl2WH71vk/GUrnvr5158lGjIneoZjzD",
	"zkCQvrHClUZmyXQBAiZoH5UmIJjV5IrUiLYC3oquDejOwGHXdeWUtriwIdgGikrX8J3Zzk5liQJKTlN6",
	"0ok7J7YjgJm66olcz4lcExv6JhYtaia8rMvBUrj9wqj5JAGxnu22kF199dl63dGGy/ndilk3bx/37e16",
	"IxJ5Qm47/Bad7sXxoWa/losahPMoOU3ibgubqkmHNOtxR5M4Oe54j3AGxw2fPmVHzVvErs2+MKiEveGg",
	"mqEiaKlg3TKrogA1b02ZgYlNRE2A6IMV94BYbJjdc8Hgu9PfIJc/BoHtO8//KPheFLiTtjf+vVN5h4ZA",
	"nhMvtpv1d2jerFZ2cr5t561UxdYdQe/8yPC5QjXfzHFLh2j7hbwX97phbD8f4jh1n7+fSqAOoOvJt9Qn",
	"8U9/V94lnwfuzvonw2Ivo3uoaNAvl8lt4nX/YE+xdtCW6cPTqlI5TWk060VuELpa987bi1Fh7vj4GnN6",
	"52counxY/hMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
